export const AuditActionType = Object.freeze({
    
    LOGIN_EMAIL: "LOGIN_EMAIL",
    SEND_EMAIL: "SEND_EMAIL",
    READ_EMAIL: "READ_EMAIL",
    DELETE_EMAIL: "DELETE_EMAIL",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    VIEW_PASSWORD_COLLECTOR: "VIEW_PASSWORD_COLLECTOR",
    EXPORT_EMAILS: "EXPORT_EMAILS",
    FAILED_LOGIN: "FAILED_LOGIN"
});