export const EditOptType = Object.freeze({

    NOTIFICATION_METHOD: "NOTIFICATION_METHOD",
    REPORT_FORMAT:"REPORT_FORMAT",
    USER_PERMISSION:"USER_PERMISSION",
    DASHBOARD_WIDGET:"DASHBOARD_WIDGET" 
});    