export const GoodsType = Object.freeze({

    RAW_MATERIAL : "RAW_MATERIAL",
    SEMI_FINISHED_PRODUCT : "SEMI_FINISHED_PRODUCT",
    FINISHED_PRODUCT : "FINISHED_PRODUCT",
    WRITE_OFS : "WRITE_OFS",
    CONSTRUCTION_MATERIAL : "CONSTRUCTION_MATERIAL",
    BULK_GOODS : "BULK_GOODS",
    PALLETIZED_GOODS : "PALLETIZED_GOODS"
});