export const GoToCategory = Object.freeze({

    ACCOUNTING : "ACCOUNTING",   
    USERS : "USERS",        
    STORAGE : "STORAGE",
    INVENTORY : "INVENTORY",
    MATERIAL_MANAGEMENT : "MATERIAL_MANAGEMENT",
    PRODUCTION_PLANNING : "PRODUCTION_PLANNING",
    QUALITY_CONTROL : "QUALITY_CONTROL",
    SALES : "SALES",
    LOGISTICS : "LOGISTICS",     
    SETTINGS : "SETTINGS",      
    REPORTS : "REPORTS",       
    GENERAL : "GENERAL",  
});