export const InspectionType = Object.freeze({

    "INCOMING" :INCOMING,
    "IN_PROCESS" :IN_PROCESS,
    "FINAL_INSPECTION" : FINAL_INSPECTION,
    "PRE_SHIPMENT" : PRE_SHIPMENT,
    "POST_DELIVERY" : POST_DELIVERY, 
    "AUDIT" : AUDIT,
    "SAMPLING" : SAMPLING
});