export const InventoryStatus = Object.freeze({

    "PENDING": PENDING,        
    "IN_PROGRESS": IN_PROGRESS,  
    "COMPLETED": COMPLETED,      
    "CANCELLED": CANCELLED,     
    "RECONCILED": RECONCILED,    
    "PARTIALLY_COMPLETED": PARTIALLY_COMPLETED ,
    "PENDING_APPROVAL": PENDING_APPROVAL,
    "APPROVED" : APPROVED 
});