export const PermissionResourceType = Object.freeze({

    // SKLADISTE
    INVENTORY : "INVENTORY",
    INVENTORY_ITEM : "INVENTORY_ITEM",
    STORAGE : "STORAGE",
    MATERIAL_MOVEMENT : "MATERIAL_MOVEMENT",
    PRODUCT : "PRODUCT",
    GOODS : "GOODS",
    SUPPLY : "SUPPLY",
    OUTBOUND_DELIVERY : "OUTBOUND_DELIVERY",
    INBOUND_DELIVERY : "INBOUND_DELIVERY",
    SHELF : "SHELF",
    BAR_CODE : "BAR_CODE",

    // LOGISTIKA
    SALES_ORDER : "SALES_ORDER",
    DELIVERY_ITEM : "DELIVERY_ITEM",
    DRIVER : "DRIVER",
    LOGISTICS_PROVIDER : "LOGISTICS_PROVIDER",
    VEHICLE : "VEHICLE",
    ROUTE : "ROUTE",
    SHIPMENT : "SHIPMENT",
    TRANSPORT_ORDER : "TRANSPORT_ORDER",

    // MATERIJALI
    MATERIAL : "MATERIAL",
    BILL_OF_MATERIAL : "BILL_OF_MATERIAL",
    MATERIAL_REQUEST : "MATERIAL_REQUEST",
    MATERIAL_REQUIREMENT : "MATERIAL_REQUIREMENT",
    MATERIAL_TRANSACTION : "MATERIAL_TRANSACTION",
    RAW_MATERIAL : "RAW_MATERIAL",

    // PLANIRANJE PROIZVODNJE
    CAPACITY_PLANNING : "CAPACITY_PLANNING",
    CONFIRMATION_DOCUMENT : "CONFIRMATION_DOCUMENT",
    WORK_CENTER : "WORK_CENTER",
    TRACKING_INFO : "TRACKING_INFO",
    STOCK_TRANSFER : "STOCK_TRANSFER",
    STOCK_ITEM_TRANSFER : "STOCK_ITEM_TRANSFER",
    PRODUCTION_ORDER : "PRODUCTION_ORDER",
    SHIFT : "SHIFT",
    SHIFT_REPORT : "SHIFT_REPORT",
    SHIFT_PLANNING : "SHIFT_PLANNING",
    REPORT : "REPORT",

    // RACUNOVODSTVO
    ACCOUNT : "ACCOUNT",
    BALANCE_SHEET : "BALANCE_SHEET",
    JOURNAL_ENTRY : "JOURNAL_ENTRY",
    JOURNAL_ITEM : "JOURNAL_ITEM",
    LEDGER_ENTRY : "LEDGER_ENTRY",
    INVOICE : "INVOICE",
    FISCAL_YEAR : "FISCAL_YEAR",
    FISCAL_QUARTER : "FISCAL_QUARTER",
    INCOME_STATEMENT : "INCOME_STATEMENT",
    PAYMENT : "PAYMENT",
    TRANSACTION : "TRANSACTION",
    TAX : "TAX",

    // KONTROLA KVALITETA
    INSPECTION : "INSPECTION",
    INSPECTION_DEFECT : "INSPECTION_DEFECT",
    DEFECT : "DEFECT",
    BATCH : "BATCH",
    QUALITY_CHECK : "QUALITY_CHECK",
    QUALITY_STANDARD : "QUALITY_STANDARD",
    TEST_MEASUREMENT : "TEST_MEASUREMENT",
    
    //PRODAJA & DISTRIBUCIJA
    PROCUREMENT : "PROCUREMENT",
    SALES : "SALES",
    SUPPLY_ITEM : "SUPPLY_ITEM",
    VENDOR : "VENDOR",

    // SISTEMSKI ENTITETI (globalni)
    USER : "USER",
    ROLE : "ROLE",
    LANGUAGE : "LANGUAGE",
    PERMISSION : "PERMISSION",
    OPTION : "OPTION",
    LOCALIZED_OPTION : "LOCALIZED_OPTION",
    SECURITY_SETTING : "SECURITY_SETTING",
    SYSTEM_STATE : "SYSTEM_STATE",
    SYSTEM_SETTING : "SYSTEM_SETTING",
    HELP : "HELP",
    GOTO : "GOTO",
    FILE_OPT : "FILE_OPT",
    EDIT_OPT : "EDIT_OPT",
    EMAIL_SETTING : "EMAIL_SETTING"
});