/*export const  PermisionType = [
	"VIEW_INVENTORY",
	 "CREATE_ORDER",
	 "CREATE_STORAGE_EMPLOYEE",
	 "CREATE_STORAGE_FOREMAN",
	"CREATE_STORAGE_MANAGER"];*/

export const PermisionType = Object.freeze({
	"VIEW_INVENTORY":VIEW_INVENTORY,
	 "CREATE_ORDER":CREATE_ORDER,
	 "CREATE_STORAGE_EMPLOYEE":CREATE_STORAGE_EMPLOYEE,
	 "CREATE_STORAGE_FOREMAN":CREATE_STORAGE_FOREMAN,
	"CREATE_STORAGE_MANAGER":CREATE_STORAGE_MANAGER
});	