export const ReportType = Object.freeze({
    
    // General
    USERS: "USERS",
    ACTIVITY_LOG : "ACTIVITY_LOG",

    // Skladiste
    INVENTORY : "INVENTORY",
    STOCK_MOVEMENT : "STOCK_MOVEMENT",
    STOCK_LEVELS : "STOCK_LEVELS",
    STOCK_DISCREPANCY : "STOCK_DISCREPANCY",

    // Logistika
    DELIVERY_NOTE : "DELIVERY_NOTE",
    TRANSPORT_PLAN : "TRANSPORT_PLAN",
    SHIPPING_STATUS : "SHIPPING_STATUS",

    // Racunovodstvo
    INVOICE : "INVOICE",
    PAYMENT_REPORT : "PAYMENT_REPORT",
    BALANCE_SHEET : "BALANCE_SHEET",
    PROFIT_AND_LOSS : "PROFIT_AND_LOSS",
    TAX_REPORT : "TAX_REPORT",

    // Materijali
    RAW_MATERIAL_USAGE : "RAW_MATERIAL_USAGE",
    MATERIAL_ORDER_REPORT : "MATERIAL_ORDER_REPORT",
    SUPPLY_CHAIN_REPORT : "SUPPLY_CHAIN_REPORT",

    // Proizvodnja
    PRODUCTION_PLAN : "PRODUCTION_PLAN",
    PRODUCTION_REPORT : "PRODUCTION_REPORT",
    WORK_ORDER_REPORT : "WORK_ORDER_REPORT",

    // Porudzbine
    ORDERS : "ORDERS"
});