export const RoleTypes = Object.freeze({

    "SUPER_ADMIN": SUPER_ADMIN,
    "ADMIN": ADMIN,
    "STORAGE_FOREMAN": STORAGE_FOREMAN,
    "STORAGE_EMPLOYEE": STORAGE_EMPLOYEE,
    "STORAGE_MANAGER": STORAGE_MANAGER
});