export const SeverityLevel = Object.freeze({

    TRIVIAL_SEVERITY : "TRIVIAL_SEVERITY",
    MINOR_SEVERITY : "MINOR_SEVERITY",
    MODERATE_SEVERITY : "MODERATE_SEVERITY", 
    MAJOR_SEVERITY : "MAJOR_SEVERITY",
    CRITICAL_SEVERITY : "CRITICAL_SEVERITY"
});