export const StorageType = Object.freeze({

    "PRODUCTION": PRODUCTION,
    "DISTRIBUTION": DISTRIBUTION,
    "OPEN": OPEN,
    "CLOSED": CLOSED,
    "INTERIM": INTERIM,
    "AVAILABLE": AVAILABLE,
    "SILO": SILO,
    "YARD": YARD,
    "COLD_STORAGE": COLD_STORAGE
});