export const SupplierType = Object.freeze({

    "CABAGE_SUPPLIER": CABAGE_SUPPLIER,
	"CARROT_SUPPLIER": CARROT_SUPPLIER,
	"TOMATO_SUPPLIER": TOMATO_SUPPLIER,
	"ONION_SUPPLIER": ONION_SUPPLIER,
	"BLUEBERRY_SUPPLIER": BLUEBERRY_SUPPLIER,
    "POTATO_SUPPLIER":POTATO_SUPPLIER
});
