export const SupplierType = Object.freeze({

    RAW_MATERIAL : "RAW_MATERIAL",
    MANUFACTURER : "MANUFACTURER",
    WHOLESALER : "WHOLESALER",
    DISTRIBUTOR : "DISTRIBUTOR",
    SERVICE_PROVIDER : "SERVICE_PROVIDER",
    AGRICULTURE : "AGRICULTURE",
    FOOD_PROCESSING : "FOOD_PROCESSING",
    LOGISTICS : "LOGISTICS",
    PACKAGING : "PACKAGING",
    MAINTENANCE : "MAINTENANCE"
});
