export const SystemSettingCategory = Object.freeze({

    "GENERAL": GENERAL,
    "SECURITY": SECURITY,
    "NOTIFICATIONS": NOTIFICATIONS,
    "UI": UI,
    "PERFORMANCE": PERFORMANCE,
    "EMAIL": EMAIL,
    "INTEGRATIONS": INTEGRATIONS,
    "FEATURE_FLAGS": FEATURE_FLAGS,
    "USER_MANAGEMENT": USER_MANAGEMENT
});